config/routes.rb
Rails.application.routes.draw do

  root                        'static_pages#home'
  get     'about'         =>  'static_pages#about'
  get     'author_login'  =>  'author_sessions#new'
  post    'author_login'  =>  'author_sessions#create'
  delete  'author_logout' =>  'author_sessions#destroy'
  resources :authors

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  has_secure_password
  validates :name,      presence: true, 
                        length: { maximum: 50 }
  validates :email,     presence: true, 
                        length: { maximum: 255 }, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  validates :password,  presence: true,
                        length: { minimum: 6 },
                        allow_nil: true

  def self.digest( string )
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create( string, cost: cost )
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember_author
    self.remember_token = Author.new_token
    update_attribute( :remember_digest, Author.digest( remember_token ) )
  end

  def author_authenticated?( remember_token )
    return false if remember_digest.nil?
    BCrypt::Password.new( remember_digest ).is_password?( remember_token )
  end

  def forget_author
    update_attribute( :remember_digest, nil )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include AuthorSessionsHelper
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new

  end

  def create
    @author = Author.find_by( email: params[ :session ][ :email ].downcase )
    if @author && @author.authenticate( params[ :session ][ :password ] )
      author_log_in @author
      params[ :session ][ :remember_me ] == '1' ? remember_author( @author ) : forget_author( @author )
      redirect_back_or @author
    else
      flash.now[ :danger ] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    author_log_out if author_logged_in?
    redirect_to root_url
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :logged_in_author,  only: [ :edit, :update, :destroy ]
  before_action :correct_author,    only: [ :edit, :update ]
  before_action :admin_author,        only: :destroy

  def index 
    @authors = Author.paginate( page: params[ :page ] )
  end
  
  def show
    @author = Author.find( params[ :id ] )
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new( author_params )
    if @author.save
      author_log_in @author
      flash[ :success ] = "Welcome to " + Rails.application.config.blog_title + "!"
      redirect_to @author
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find( params[ :id ] )
  end

  def update
    @author = Author.find( params[ :id ] )
    if @author.update_attributes( author_params )
      flash[ :success ] = "Profile updated"
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    Author.find( params[ :id ] ).destroy
    flash[ :success ] = "Author deleted."
    redirect_to authors_url
  end

  private

    def author_params
      params.require(:author).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in author.
    def logged_in_author
      unless author_logged_in?
        store_location
        flash[ :danger ] = "Please log in."
        redirect_to author_login_url
      end
    end

    # Confirms the correct author.
    def correct_author
      @author = Author.find( params[ :id ] )
      redirect_to( root_url ) unless current_author?( @author )
    end

    # Confirms an admin author.
    def admin_author
      redirect_to( root_url ) unless current_author.admin?
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #Page titles
  def tab_title( page_title = '' )
    if page_title.empty?
      Rails.application.config.blog_title
    else
      page_title + " | " + Rails.application.config.blog_title
    end
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper

  # Logs in the given author.
  def author_log_in( author )
    session[ :author_id ] = author.id
  end

  # Remembers an author in a persistent session.
  def remember_author( author )
    author.remember_author
    cookies.permanent.signed[ :author_id ] = author.id
    cookies.permanent[ :remember_token ] = author.remember_token
  end

  def current_author?( author )
    author == current_author
  end

  def current_author
    if ( author_id = session[ :author_id ] )
      @current_author ||= Author.find_by( id: author_id )
    elsif ( author_id = cookies.signed[ :author_id ] )
      author = Author.find_by( id: author_id )
      if author && author.author_authenticated?( cookies[ :remember_token ] )
        author_log_in author
        @current_author = author
      end
    end
  end

  def author_logged_in?
    !current_author.nil?
  end

  def forget_author( author )
    author.forget_author
    cookies.delete( :author_id )
    cookies.delete( :remember_token )
  end

  def author_log_out
    forget_author( current_author )
    session.delete( :author_id )
    @current_author = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or( default )
    redirect_to( session[ :forwarding_url ] || default )
    session.delete( :forwarding_url )
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[ :forwarding_url ] = request.url if request.get?
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/author_sessions/new.html.erb
<% provide( :title, "Author Log in" ) %>
<h1>Author Log in</h1>

<div>
  <div>
    <%= form_for( :session, url: author_login_path ) do | f | %>
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :remember_me do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>

      <%= f.submit "Log in" %>
    <% end %>
  </div>
</div>

app/views/authors/_author.html.erb
<li>
  <p>image for author</p>
  <%= link_to author.name, author %>
  <% if current_author.admin? && !current_author?( author ) %>
    | <%= link_to "delete", author, method: :delete,
                                    data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/authors/_author_form.html.erb
<%= form_for( @author ) do | f | %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/authors/edit.html.erb
<% provide( :title, "Edit author" ) %>
<h1>Update your profile</h1>

<div>
  <div>
    <%= render 'authors/author_form' %>
  </div>
</div>

app/views/authors/index.html.erb
<% provide( :title, "All authors" ) %>
<h1>All authors</h1>

<%= will_paginate %>

<ul>
  <%= render @authors %>
</ul>

<%= will_paginate %>

app/views/authors/new.html.erb
<% provide(:page_title, 'Sign up') %>
<h1>Sign up</h1>

<div>
  <div>
    <%= form_for( @author ) do | f | %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/authors/show.html.erb
<% provide(:page_title, @author.name ) %>

<div>
  <aside>
    <section>
      <h1>
        <p>(user image: feature pending. see CH 7.1.4 for gravatar equivalent)</p>
        <%= @author.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <%= render 'layouts/nav_bar' %>
    <p>©2015 Jason Hopper | Spectre6000</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= link_to "#{Rails.application.config.blog_title}", '#' %>
    <%= render 'layouts/nav_bar' %>
  </div>
</header>

app/views/layouts/_nav_bar.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <% if author_logged_in? %>
      <li><%= link_to "Authors", authors_path %></li>
      <li><a href="#">Account</a></li>
      <ul>
        <li><%= link_to "Profile", current_author %></li>
        <li><%= link_to "settings", edit_author_path(current_author) %></li>
        <li><%= link_to "Log out", author_logout_path, method: 'delete' %></li>
      </ul>
    <% else %>
      <li><%= link_to "Log in", author_login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= tab_title( yield( :page_title ) ) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script> <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div>
      <% flash.each do | meassage_type, message | %>
        <div>
          <%= message %>
        </div>
      <% end %> 
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

    <%= debug( params ) if Rails.env.development? %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @author.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize( @author.errors.count, "error" ) %>.
    </div>
    <ul>
      <% @author.errors.full_messages.each do | msg | %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:page_title, "About") %>

<p>about</p>

app/views/static_pages/home.html.erb
<p>home</p>